# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: mysql+pymysql://root:password@mariadb/homeassistant?charset=utf8mb4
  purge_keep_days: 30
  commit_interval: 1

nut:
  - name: Ippon UPS
    host: nut
    port: 3493
    username: upsmon
    password: upsmonpass
    resources:
      - battery.charge
      - battery.runtime
      - battery.voltage
      - input.voltage
      - output.voltage
      - ups.status

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: telegram_ups
    chat_id: !secret telegram_chat_id